const stats = [
  { value: "500+", label: "Active Traders", description: "Learning and growing daily" },
  { value: "87%", label: "Win Rate", description: "Average across all setups" },
  { value: "$2.4M", label: "Total Profits", description: "Generated by our community" },
  { value: "150+", label: "Video Lessons", description: "Comprehensive strategy guides" },
];

const StatsSection = () => {
  return (
    <section id="results" className="py-24 relative">
      {/* Background Accent */}
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-primary/5 to-transparent" />
      
      <div className="container mx-auto px-6 relative z-10">
        <div className="text-center max-w-2xl mx-auto mb-16">
          <h2 className="font-display text-4xl md:text-5xl font-bold mb-4">
            Proven <span className="text-gradient">Results</span>
          </h2>
          <p className="text-lg text-muted-foreground">
            Real numbers from real traders using our strategy every day.
          </p>
        </div>

        <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-6">
          {stats.map((stat, index) => (
            <div
              key={stat.label}
              className="text-center p-8 rounded-2xl glass hover:border-primary/30 transition-all duration-300"
            >
              <div className="font-display text-5xl md:text-6xl font-bold text-gradient mb-2">
                {stat.value}
              </div>
              <div className="font-semibold text-foreground mb-1">
                {stat.label}
              </div>
              <div className="text-sm text-muted-foreground">
                {stat.description}
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default StatsSection;
